# Escolhe uma imagem base com Python
FROM python:3.11-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o script local para dentro do container
COPY carguru.py .

# Define o comando que será executado ao rodar o container
CMD ["python", "carguru.py"]