# Usa uma imagem base com Python
FROM python:3.11-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o script Python para dentro do container
COPY mascarar.py .

# Define o comando padrão a ser executado ao iniciar o container
CMD ["python", "mascarar.py"]